language: java
sudo: false

addons:
  apt:
    package: &global_deps
      - ksh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      services:
        - xvfb
      addons:
        apt:
          packages:
            - *global_deps
            - at-spi2-core
            - build-essential
            - libgtk-3-dev
            - libxtst-dev
    - os: osx
      osx_image: xcode10.1
      # env: PRINT_CRASH_LOGS="true"

before_script:
  - export JAVA_OPTS=-Xmx8192m
  - echo $JAVA_OPTS
  - sh ./gradlew --version
  # set java_home (for Mac)
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi

install: true

script: ./gradlew --info build

deploy:
  # Deploy snapshots on every commit pushed to master
  - provider: script
    script: ./gradlew publish -PsonatypeUsername=$SONATYPE_USERNAME -PsonatypePassword=$SONATYPE_PASSWORD
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux

  # Deploy releases on every tag push
  - provider: script
    script: bash .ci/deploy.sh
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux