language: java
sudo: false

jdk: openjdk11

addons:
  apt:
    package: &global_deps
      - ksh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: bionic
      services:
        - xvfb
      addons:
        apt:
          packages:
            - *global_deps
            - at-spi2-core
            - build-essential
            - libgl-dev
            - libgtk-3-dev
            - libxtst-dev
            - libavcodec-dev
            - libavformat-dev
            - libasound2-dev
      before_script:
        - mkdir -p $HOME/graalvm && cd $HOME/graalvm
        - export GRAALVM_GITHUB_LINUX_AMD64_DOWNLOAD_URL=$(curl -s https://api.github.com/repos/graalvm/graalvm-ce-dev-builds/releases | grep browser_download_url | grep graalvm-ce-java11-linux-amd64 | head -n 1 | sed -e 's/.*\(https.*\)".*/\1/g')
        - wget $GRAALVM_GITHUB_LINUX_AMD64_DOWNLOAD_URL
        - tar -xzvf graalvm-ce-java11-linux-amd64-20.2.0-dev.tar.gz && cd $TRAVIS_BUILD_DIR
        - mkdir -p $HOME/javafx-static-libs-linux && cd $HOME/javafx-static-libs-linux
        - wget https://download2.gluonhq.com/substrate/javafxstaticsdk/openjfx-15-latest-linux-x86_64-static.zip
        - unzip openjfx-15-latest-linux-x86_64-static.zip && cd $TRAVIS_BUILD_DIR
        - export GRAALVM_HOME=$HOME/graalvm/graalvm-ce-java11-20.2.0-dev
        - export JAVAFX_STATIC_SDK=$HOME/javafx-static-libs-linux/sdk
        - export JAVA_HOME=$GRAALVM_HOME
    - os: osx
      osx_image: xcode10.2
      before_script:
        - mkdir -p $HOME/graalvm && cd $HOME/graalvm
        - export GRAALVM_GITHUB_DARWIN_AMD64_DOWNLOAD_URL=$(curl -s https://api.github.com/repos/graalvm/graalvm-ce-dev-builds/releases | grep browser_download_url | grep graalvm-ce-java11-darwin-amd64 | head -n 1 | sed -e 's/.*\(https.*\)".*/\1/g')
        - wget $GRAALVM_GITHUB_DARWIN_AMD64_DOWNLOAD_URL
        - tar -xzvf graalvm-ce-java11-darwin-amd64-20.2.0-dev.tar.gz && cd $TRAVIS_BUILD_DIR
        - mkdir -p $HOME/javafx-static-libs-darwin && cd $HOME/javafx-static-libs-darwin
        - wget https://download2.gluonhq.com/substrate/javafxstaticsdk/openjfx-15-latest-darwin-x86_64-static.zip
        - unzip openjfx-15-latest-darwin-x86_64-static.zip && cd $TRAVIS_BUILD_DIR
        - mkdir -p $HOME/javafx-static-libs-ios && cd $HOME/javafx-static-libs-ios
        - wget https://download2.gluonhq.com/substrate/javafxstaticsdk/openjfx-15-latest-ios-arm64-static.zip
        - unzip openjfx-15-latest-ios-arm64-static.zip && cd $TRAVIS_BUILD_DIR
        - export GRAALVM_HOME=$HOME/graalvm/graalvm-ce-java11-20.2.0-dev/Contents/Home
        - export JAVAFX_STATIC_SDK=$HOME/javafx-static-libs-darwin/sdk
        - export JAVAFX_STATIC_SDK_IOS=$HOME/javafx-static-libs-ios/sdk
        - export JAVA_HOME=$GRAALVM_HOME

before_script:
  - echo $JAVA_OPTS
  - sh ./gradlew --version

install: true

script: ./gradlew --info build
